// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm9IXBNOhU8ujToVbNecSD0Sqmb9z-y6Q',
    appId: '1:1070020256989:web:f4a3fd3a3b328b54a52734',
    messagingSenderId: '1070020256989',
    projectId: 'devmet-1167c',
    authDomain: 'devmet-1167c.firebaseapp.com',
    storageBucket: 'devmet-1167c.appspot.com',
    measurementId: 'G-GJ80VBFKRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2jM6a1oIVpldPyjSPHQVMvi3TLeg2-Mo',
    appId: '1:1070020256989:android:966820f70c0dd66ea52734',
    messagingSenderId: '1070020256989',
    projectId: 'devmet-1167c',
    storageBucket: 'devmet-1167c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKHYl3Xvq_KxB2CgBtygrChBKVBtbxrao',
    appId: '1:1070020256989:ios:2af852333d7b98f0a52734',
    messagingSenderId: '1070020256989',
    projectId: 'devmet-1167c',
    storageBucket: 'devmet-1167c.appspot.com',
    iosClientId: '1070020256989-tbkotriaru2kedn6u5e3b6vonomhjb73.apps.googleusercontent.com',
    iosBundleId: 'com.zero.devmet',
  );
}
